### PR TITLE
Translation of Examples from cubicaltt.

### PR DESCRIPTION
**Pull request by xekoukou**
I intend to translate some examples from cubicaltt to agda. Would you be interested in adding them here?

### CODE REVIEW

**Comment by Saizan** [comment]
Yes! Having more examples would be great!

I've been busy traveling but I'll look at the pull request tomorrow, sounds like it should be merged.

**Comment by xekoukou** [comment]
I noticed that ```subst``` and ```transpP``` are the same except that ```transpP``` transports ```id``` with the ```A``` while ```subst``` transports the value itself.

Can we prove that they are equal?

```
transpP≡subst : ∀ {ℓ ℓ'} {A : Set ℓ}{B : A → Set ℓ'} {x y : A} → (p : x ≡ y) → (p0 : B x) → transpP {B = B} p p0 ≡ subst {P = B} x y p p0
transpP≡subst {B = B} {x} {y} p p0 i = {!!}
```

It seems that in order to prove that we need to prove these lemmas : 
```
boo : ∀{ℓb} → {B : Set ℓb} → {ℓa : I → Level} → (A : (i : I) → Set (ℓa i)) → (f : (B → A i0)) → (λ x → transp A (f x)) ≡ transp (λ i → (B → A i)) f
boo {B = B} A f i x = {!!} 

foo : ∀{ℓb} → {B : Set ℓb} → (x : B) → primComp (λ j → B) i0 (λ j → empty) x ≡ x
foo {B = B} x i = {!!}
```

Can you help with these? My geometric intuition fails when we are at the low dimensions 
```primComp _ i0 _ _``` seems to be a point.
```primComp _ i1 _ _``` seems to be a line.


It seems that ```primComp (\ i -> B -> A i)``` is transformed into a composition of two ```primComp```.


update : Ok , I proved them. See next commit.

**Comment by xekoukou** [comment]
Added Elimination rules for Equivalences and Isomorphism + another formulation of Univalence.

**Comment by xekoukou** [comment]
Added the "binnat.ctt" example.

**Comment by Saizan** [comment]
Hi, 

seems like you forgot to add some files, like Retract.agda, it's imported by Univalence but not in the repo.

**Comment by xekoukou** [comment]
Done.

**Comment by xekoukou** [comment]
I hope to have put them all now :).

**Pull request merged**
