### PR TITLE
Retraction preserve all homotopy levels

### PR DESCRIPTION
**Pull request by fredefox**
Again - builds on #20 and #21 

I've reverted f48645aae39bcd24a52424ad58b9ad2987984aab in 184e4cd286056974af5ca3e975c16ea267ea3dca as requested.

Please also see 4f5ad584d3a762604912a0dc10c01b711f9ac73f as this PR contains unfinished code. I've included my attempt as commented code and postulated the result (so `make` goes through). It's a bit of a mess, sorry for that.

### CODE REVIEW

**Comment by Saizan** [comment]
Great!  

How much attached are you to the current definition of ```HasLevel```? It would be much more uniform to define it like so:

```
  HasLevel : TLevel → Set ℓ → Set ℓ
  HasLevel ⟨-2⟩     = isContr
  HasLevel (S n) A = (x y : A) → HasLevel n (x ≡ y)
```

Then you would have only two cases in ```transportNType``` and ```HasLevel (S n) A -> {x y : A} -> HasLevel n (x \== y)``` would be automatic.

**Comment by Saizan** [comment]
you could then have simple conversion functions between ```isProp A``` and ```HasLevel <-1>```

**Comment by fredefox** [comment]
I didn't define it like you said for two reasons: I didn't know if this was an equivalent formulation and also because the way it's defined now `HasLevel 1 A` is *judgmentally* equal to `IsProp A` and so on for `IsSet A` etc..

**Comment by Saizan** [comment]
Fair enough, I will fill in the postulates this morning and then push it

**Pull request merged**
